apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
     #soft limit
      requests:
        memory: "1Mi" #RAM
        cpu: "1m" #CPU  
      # hard limit, how much it can go upto
      limits:
        memory: "1Mi" #RAM
        cpu: "1m" #CPU  